### ISSUE TITLE
Can't drag EntityConfig into ObjectReference in System graph

### ISSUE THREAD

**Issue by neon-age** [chromealex/ME.BECS#2]
![image](https://github.com/chromealex/ME.BECS/assets/29812914/3e2769a3-000f-4fb3-bd43-c9fae54bc7f5)
![image](https://github.com/chromealex/ME.BECS/assets/29812914/4f898e7a-9687-4d5a-81bc-e72a628dd293)

**Comment by chromealex** [comment]
fixed in 2023.6.1-a.5: added "Config" type
