### ISSUE TITLE
ViewsModule world initialization error after View prefab was deleted from assets

### ISSUE THREAD

**Issue by neon-age** [chromealex/ME.BECS#4]
![image](https://github.com/chromealex/ME.BECS/assets/29812914/59469b7c-b568-424d-a008-f87c4d553be7)

This happens every time and completely prevents world initialization.

Can't find a fix for this, I've tried:
Re-launching Editor 
Re-adding ProjectInitializer component
Re-creating ViewsModule asset

Nothing helps, except disabling this module.

**Comment by chromealex** [comment]
fixed in 2023.6.1-a.2
