### ISSUE TITLE
Full component type name (when nested in other type) is not displayed in EntityConfig 

### ISSUE THREAD

**Issue by neon-age** [chromealex/ME.BECS#6]
![image](https://github.com/chromealex/ME.BECS/assets/29812914/bad841c0-972c-4c33-8b20-32b18acae74b)

![image](https://github.com/chromealex/ME.BECS/assets/29812914/e2875ae5-2e59-4536-a3c2-e3f794c26849)

**Comment by chromealex** [comment]
Add more components to see different namespaces.
